server/app.py
import queue
import webbrowser

import flask
from flask import render_template, request

# cheet internals
from config import config

# blueprints
from views.api import api
from views.web_interface import interface
from views.display import display
from views.editpage import editpage

app = flask.Flask(__name__)
DEBUG = True

app.register_blueprint(api)
app.register_blueprint(interface)
app.register_blueprint(display)
app.register_blueprint(editpage)


if __name__ == "__main__":
    if not DEBUG:
        webbrowser.get().open('http://localhost:8765')
    app.run(debug=DEBUG, port="8765")

server/views/api.py
import html

from flask import Blueprint, render_template, request, redirect

from core.cheet import Cheet
from db import db
from config import config


api = Blueprint('api', __name__,
                template_folder='templates')

def extract_cheet(form):
    """escape html from form fields and return cheet"""
    d = {}
    for key in form.keys():
        d[key] = html.unescape(form.get(key))
    cheet = Cheet.from_dict(d)
    return cheet

@api.route('/configure/cheetfilter', methods=['POST'])
def configure_cheetfilter():
    field = request.form.get('field')
    val = request.form.get('value')
    config['cheetfilter'] = (field, val)
    if request.form.get('clear') is not None:
        del config['cheetfilter']
    return redirect('/')

@api.route('/update', methods=["POST"])
def update():
    """updates display with selected cheets"""
    cheet = extract_cheet(request.form)
    db.update(cheet)

    return redirect('/')

@api.route('/get', methods=['GET', 'POST'])
def get():
    """return json string of cheets"""
    if request.method == 'POST':
        searchfor = request.form['searchfor']
        searchin = request.form['searchin']
        db.get_by(searchin, searchfor)
    else:
        return Cheet.schema.dumps(cm.cheets, many=True)

@api.route('/create', methods=["POST"])
def create():
    """create a cheet from formdata"""
    cheet = extract_cheet(request.form)
    db.create(cheet)
    return redirect('/')

@api.route('/delete/<id>', methods=['GET'])
def delete(id):
    """delete cheet by id"""
    db.delete(id)
    return redirect('/')

@api.route('/addtag/<id>')
def addtag(id):
    cheet = db.get(id)
    cheet.tags.append('newtag')
    return redirect('/')

@api.route('/remtag/<id>/<tag>')
def remtag(id, tag):
    cheet = db.get(id)
    cheet.tags = cheet.tags.remove(tag)
    db.update(cheet)
    return redirect('/')

@api.route('/vimedit/<id>', methods=['GET'])
def vimedit(id):
    """open vim in the server process to edit a cheet by id"""
    if id in 'newcheet':
        cheet = Cheet('required','required','required','required')
    else:
        cheet = db.get(id)
    cheet = cheet.vim_edit()
    db.update(cheet)
    return redirect('/')

server/views/display.py
import queue

from flask import render_template, request, Blueprint, Response

from db import db

# from https://maxhalford.github.io/blog/flask-sse-no-deps/
"""Serves an SSE-based updating display of cheets"""

display = Blueprint('display', __name__,
                template_folder='templates')


class CheetDispatcher:
    """handles dispatch of the cheet sheet to the browser.  I need to
    better understand how this works"""

    def __init__(self):
        self.listeners = []
        self.selector = None

    def listen(self):
        q = queue.Queue(maxsize=5)
        self.listeners.append(q)
        return q

    def update(self):
        if selector is None:
            cheets = db.cheets
        else:
            cheets = db.get_by(selector[0], selector[1])
        msg = render_template("basic.j2", cheets = cheets)
        for i in reversed(range(len(self.listeners))):
            try:
                self.listeners[i].put_nowait(msg)
            except queue.Full:
                del self.listeners[i]


dispatcher = CheetDispatcher()


@display.route('/listen')
def listen():
    """registers a browser as a listener"""

    def stream():
        messages = dispatcher.listen()
        while True:
            msg = messages.get()
            yield msg

    return Response(stream())

# @api.route('/updateview/<id>', methods=["POST"])
def display_update(id):
    """updates display with selected cheets"""

    msg = format_sse(data='pong')
    dispatcher.update()
    return "updated cheets", 200



def format_sse(data: str, event=None):
    msg = f'data: {data}\n\n'
    if event is not None:
        msg = f'event: {event}\n{msg}'
    return msg

server/views/editpage.py
from flask import Blueprint, render_template

from db import db
from config import config

editpage = Blueprint('editpage', __name__,
                     template_folder='templates')


@editpage.route('/')
def home():
    if (cheetfilter := config.get('cheetfilter')) is not None:
        cheets = db.get_by(cheetfilter[0], cheetfilter[1])
    else:
        cheets = db.cheets
    page = render_template("editpage.j2", cheets = cheets, config=config)
    return page

server/views/web_interface.py
from flask import Blueprint, render_template

from db import db

interface = Blueprint('interface', __name__,
                template_folder='templates')

@interface.route('/edit/<cheetid>')
def edit_cheet(cheetid):

    cheet = db.get(id)
    return render_template('edit_cheet.j2', cheet=cheet)

server/templates/basic.j2
<!DOCTYPE html>

<html>
  <head>
    <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='styles/basic.css')}}">
    <script>
      var source = new EventSource('/listen');
      source.onmessage = function (event) {
      alert(event.data)
      }
    </script>
  </head>
  <body>
    <div class="sheet-page-container">
      {% for cheet in cheets %}
	<div class="cheet-container">
	  <div class="cheet-header-container">
	    <p class="cheet-title">{{ cheet.name }}</p>
	    <p class="cheet-context">{{ cheet.context }}</p>
	    <kbd class="cheet-kb">{{ cheet.key }}</kbd>
	  </div>
	  <div class="cheet-desc-container">
	    <p class="cheet-desc">{{ cheet.description }}</p>
	  </div>
	  <p class="cheet-note">
	    {% if cheet.note %}
	      {{ cheet.note }}
	    {% else %}
	      No notes.
	    {% endif %}
	  </p>
	  <ul class="cheet-tag-list">
	    <lh class="cheet-tag-list-header">Tags:</lh>
	    {% if cheet.tags %}
	      {% for tag in cheet.tags %}
		<li class="cheet-tag-item">{{ tag }}</li>
	      {% endfor %}
	    {% endif %}
	  </ul>
	</div>
      {% endfor %}

    </div>
  </body>
</html>

server/templates/editpage.j2
<!DOCTYPE html>

<html>
    <head>
      <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='styles/basic.css')}}">
      <script>
	var source = new EventSource('/listen');
	source.onmessage = function (event) {
	    alert(event.data)
	}
      </script>
    </head>
    <body>
      <div class="control-panel">
	<form method="POST" action="/configure/cheetfilter">
	    <select name="field" id="fieldselector">
		<option value="context">context</option>
		<option value="tags">tag</option>
		<option value="name">name</option>
	    </select>
	    <input type="text" name="value"></input>
	    <input type="submit" value="filter"></input>
	</form>
	<form method="POST" action="/configure/cheetfilter">
	    <input type="hidden" value="clear" name="clear"></input>
	    <input type="submit" value="clear filters"></input>
	</form>
	{% if config['cheetfilter'] %}
	    <p>Filtering by {{ config['cheetfilter'][0] }} = {{ config['cheetfilter'][1] }}</p>
	{% endif %}

      </div>

	<div class="sheet-page-container">
	  {% for cheet in cheets %}
	    <form method="POST" action="/update">
	      <input type='hidden' class='id' id='id' name="id" value="{{ cheet.id }}">
	      <div class="cheet-container">
		<div class="cheet-header-container">
		  <p contenteditable id="title-{{ cheet.id }}" class="fauxinput name">{{ cheet.name }}</p>
		  <input type="hidden">
		  <div class="cheet-header-bind-container">
		    <p contenteditable id="context-{{ cheet.id }}" class="fauxinput context">{{ cheet.context }}</p>
		    <kbd contenteditable id="key-{{ cheet.id }}" class="fauxinput key">{{ cheet.key }}</kbd>
		  </div>
		</div>
		<div class="cheet-desc-container">
		  <p contenteditable id="desc-{{ cheet.id}}" class="fauxinput description">{{ cheet.description }}</p>
		</div>
		<p contenteditable id="note-{{ cheet.id }}" class="fauxinput note">{{ cheet.note }}</p>
		<ul class="cheet-tag-list">
		  <lh class="cheet-tag-list-header">Tags:</lh>
		  {% if cheet.tags %}
		    {% for tag in cheet.tags %}
		      <li>
			  <p contenteditable class="fauxinput tag-item">{{ tag }}</p>
			  <button
			      type='button'
			      onclick="location.href='{{
						      url_for('api.remtag',
							  id=cheet.id,
							  tag=tag
						      )}}'">-</button>
		      </li>
		    {% endfor %}
		  {% endif %}
		</ul>
		<button type='button' onclick="location.href='{{
					       url_for('api.addtag', id=cheet.id )}}'">
					       +</button>
	      </div>
	      <input type="submit" value="update">
	      <button type='button' onclick="location.href='{{ url_for('api.delete', id=cheet.id ) }}'">delete</button>
	      <button type='button' onclick="location.href='{{ url_for('api.vimedit', id=cheet.id ) }}'">vim!</button>
	    </form>
	    {% endfor %}

	    <form method="POST" action="/create">
	      <div class="cheet-container">
		<div class="cheet-header-container">
		  <p contenteditable id="title-new" class="fauxinput name">new cheet</p>
		  <input type="hidden">
		  <p contenteditable id="context-new" class="fauxinput context">context</p>
		  <kbd contenteditable id="key-new" class="fauxinput key">key</kbd>
		</div>
		<div class="cheet-desc-container">
		  <p contenteditable id="desc-new" class="fauxinput description">description goes here</p>
		</div>
		<p contenteditable id="note-new" class="fauxinput note">
		  Note
		</p>
		<ul class="cheet-tag-list">
		  <lh class="cheet-tag-list-header">Tags:</lh>
		  <li>TODO</li>
		  <li>tags</li>
		</ul>
	      </div>
	      <input type="submit" value="create">

	      <button type='button' onclick="location.href='{{ url_for('api.vimedit', id='newcheet' ) }}'">vim!</button>
	    </form>

      <script src="{{ url_for('static', filename='formsender.js')}}"></script>

	</div>
    </body>
</html>